/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arbolhuffmanavl_abi;

import javax.swing.JOptionPane;

/**
 *
 * @author Abigail
 */
public class Interface extends javax.swing.JFrame {
public String huffman = "";
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbol2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        arbol1 = new javax.swing.JTextArea();
        HUFFMAN = new javax.swing.JButton();
        AVL = new javax.swing.JButton();
        CERRAR = new javax.swing.JButton();
        LIMPIAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("¿CUANTOS VALORES QUIERE INGRESAR?");

        jLabel2.setText("ARBOL ORIGINAL");

        jLabel3.setText("ARBOL BALANCEADO");

        arbol2.setColumns(20);
        arbol2.setRows(5);
        jScrollPane1.setViewportView(arbol2);

        arbol1.setColumns(20);
        arbol1.setRows(5);
        jScrollPane2.setViewportView(arbol1);

        HUFFMAN.setText("HUFFMAN");
        HUFFMAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HUFFMANActionPerformed(evt);
            }
        });

        AVL.setText("AVL");
        AVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AVLActionPerformed(evt);
            }
        });

        CERRAR.setText("CERRAR");
        CERRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CERRARActionPerformed(evt);
            }
        });

        LIMPIAR.setText("LIMPIAR");
        LIMPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIMPIARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(HUFFMAN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AVL))
                            .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(LIMPIAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CERRAR)))
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HUFFMAN)
                    .addComponent(AVL))
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CERRAR)
                    .addComponent(LIMPIAR))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HUFFMANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HUFFMANActionPerformed
        // TODO add your handling code here:
                  arbol1.setText("Cadena Original \n");
        	  int N = Integer.parseInt(valor.getText());
                    Arbol x=new Arbol();
                  Trees arbolAVL = new Trees();
		      for(int i=1; i<=N;i++){
		        int v= Integer.parseInt(JOptionPane.showInputDialog("Ingrese valor " + i));
		        arbol1.setText(arbol1.getText()+v+"  ");
		        x.insertarNodo(v);
		        arbolAVL.insert(v);
        	 } 
                      
            arbol2.setVisible(false);
        	
            String value = valor.getText();
            int[] charFreqs = new int[256];
            for (char c : value.toCharArray()) {
                charFreqs[c]++;
            }
    		arbol1.setText(arbol1.getText()+("Cadena original: "+value)+"\n");
    		HuffmanTree arbol = Abigail_Huffman.construirArbol(charFreqs);
    		
    		arbol1.setText(arbol1.getText()+""+Abigail_Huffman.imprimir(arbol, new StringBuffer()));
        
        
    }//GEN-LAST:event_HUFFMANActionPerformed

    private void AVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AVLActionPerformed
        // TODO add your handling code here:
        
         arbol1.setText("Cadena Original \n");
        	  int N = Integer.parseInt(valor.getText());
              Arbol x=new Arbol();
              Trees arbolAVL = new Trees();
		      for(int i=1; i<=N;i++){
		        int v= Integer.parseInt(JOptionPane.showInputDialog("Ingrese valor " + i));
		        arbol1.setText(arbol1.getText()+v+"  ");
		        x.insertarNodo(v);
		        arbolAVL.insert(v);
       } 
        arbol1.setText(arbol1.getText()+("\nRecorrido Preorden \n"+x.imprimirPreorden()+"\nRecorrido Inorden \n"+x.imprimirInorden()+"\nRecorrido Postorden \n"+x.imprimirPostorden()));
         
        arbol2.setText("AVL. Arbol balanceado"+arbolAVL.imprimirPorNiveles());
         arbol2.setText(arbol2.getText()+"\n-------------------------------------");
        arbol2.setText(arbol2.getText()+("\nPreorden balanceado\n"+arbolAVL.imprimirPreorden())+("\nInorden balanceado\n"+arbolAVL.imprimirInorden())+("\nPosorden balanceado\n"+arbolAVL.imprimirPosorden()));
    
    }//GEN-LAST:event_AVLActionPerformed

    private void CERRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CERRARActionPerformed
        // TODO add your handling code here:
          System.exit(0);
    }//GEN-LAST:event_CERRARActionPerformed

    private void LIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIMPIARActionPerformed
        // TODO add your handling code here:
        valor.setText("");
        arbol1.setText("");
        arbol2.setText("");
    }//GEN-LAST:event_LIMPIARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AVL;
    private javax.swing.JButton CERRAR;
    private javax.swing.JButton HUFFMAN;
    private javax.swing.JButton LIMPIAR;
    private javax.swing.JTextArea arbol1;
    private javax.swing.JTextArea arbol2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
